@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Diagrama de component omnichannel parcial

'LAYOUT_WITH_LEGEND()

AddRelTag("async", $lineStyle = DashedLine())

Container(AplicativoWeb, "Aplicativo Web", "Tecnologias de front web", "Pagina de interaçao com o cliente")
Container(Aplicativomobile, "Aplicativo Mobile", "Tecnologia mobile", "Aplicação de interaçao com o cliente")
System_Ext(ViaCepApi, "Api ViaCep", "Api externa de Validação e busca de endereço")
Container(NotificacaoApi, "Api de Notificação", ".Net", "Api responsávelo pelo processo de notificações")
ContainerDb(customerDb, "CustomberDb", "InMemoryDatabase 'para esse pedaço de projeto'", "Guarda dados de cliente")

System_Boundary(boundary, "Api de Cliente"){
    Component(ControladorDeCliente, "Controlador de Cliente", "Reponsavel por cadastro/busca de dados de cliente")
    Component(ControladorDeEndereço, "Controlador de Endereço", "Reponsavel por cadastro/busca de dados de cliente")
}

Rel_Down(AplicativoWeb, ControladorDeCliente, "Realiza cadastro/busca de dados de clientes via")
Rel_Down(AplicativoWeb, ControladorDeEndereço, "Realiza validação/busca de dados de endereço via de compras via")
Rel_Down(Aplicativomobile, ControladorDeCliente, "Realiza cadastro/busca de dados de clientes via")
Rel_Down(Aplicativomobile, ControladorDeEndereço, "Realiza validação/busca de dados de endereço via de compras via")

Rel(ControladorDeCliente, ControladorDeEndereço, "Busca/Valida dados de endereço via")
Rel(ControladorDeEndereço, ControladorDeCliente, "Retorna dados de endereço para")
Rel(ControladorDeEndereço, Aplicativomobile, "Retorna dados de endereço para")
Rel(ControladorDeEndereço, AplicativoWeb, "Retorna dados de endereço para")

Rel(ControladorDeEndereço, ViaCepApi, "Realiza Check de CEP via")
Rel(ViaCepApi, ControladorDeEndereço, "Retorna Dados de CEP para")

Rel(ControladorDeCliente, NotificacaoApi, "Notifica usuario via", "Utilizando Mensageria", $tags="async")

Rel(ControladorDeCliente, customerDb, "Guarda e busca dados em","EFCore")
@enduml